#!/bin/sh

UNIT=openivi

. /etc/formfactor/config

SHOWCURSOR="no"

# Disable screen blanking
xset s off -dpms

# Start on-screen keyboard in 'remote-control' mode
matchbox-keyboard -d small &

case $UNIT in
	openivi)
                if [ -n "$(xinput | grep Multi-touch)" ]; then
		# Gen2
                        xrandr --newmode 1280x800   83.50  1280 1352 1480 1680  800 803 809 831 -hsync +vsyn
                        xrandr --addmode HDMI1 1280x800
                        xrandr --output HDMI1 --mode 1280x800 --auto
                        xinput map-to-output "pointer:Chalkboard Electronics HID Multi-touch" HDMI1
                else
		# Gen1
                        xrandr --newmode 1280x800   83.50  1280 1352 1480 1680  800 803 809 831 -hsync +vsyn
                        xrandr --addmode HDMI1 1280x800
                        xrandr --output HDMI1 --mode 1280x800 --rotate inverted --auto
                        xinput map-to-output "Chalkboard Electronics HID Touchscreen" HDMI1
                fi
                ;;
	rimova)
		xrandr --newmode 1024x768p 64.11 1024 1080 1184 1344 768 769 772 795 -HSync +Vsync
		xrandr --addmode HDMI1 1024x768p
		xrandr --output HDMI1 --mode 1024x768p
		;;
esac

# Hack until we have connman 1.31
# https://01.org/connman/blogs/pflykt/2015/connman-1.31
# with connmand-wait-online.target
until connmanctl state | grep -q online
do
	echo "Waiting for a network connection..."
	sleep 1
done

openivi-html5 -f -u http://localhost:8000 &

START_APPLETS=showdesktop,windowselector
END_APPLETS=clock,battery,systray,startup-notify,notify
END_APPLETS=openmoko-panel-gsm,$END_APPLETS # feature-phone

matchbox-panel --titlebar --start-applets $START_APPLETS --end-applets $END_APPLETS &

exec matchbox-window-manager -theme Sato -use_desktop_mode decorated -use_cursor $SHOWCURSOR $@
