#!/bin/sh

if [ "$HAVE_TOUCHSCREEN" = "1" ]; then
    SHOWCURSOR="no"
else
    SHOWCURSOR="yes"
fi

if [ "$HAVE_KEYBOARD" = "1" ]; then
    KEYBOARD_APPLET=""
else
    KEYBOARD_APPLET="keyboard"
fi

xrandr --newmode 1024x768p 64.11 1024 1080 1184 1344 768 769 772 795 -HSync +Vsync
xrandr --addmode HDMI1 1024x768p
xrandr --output HDMI1 --mode 1024x768p

xmodmap -e "keycode 121 = KP_Subtract"
xmodmap -e "keycode 134 = KP_Add"
xmodmap -e "keycode 122 = Down"
xmodmap -e "keycode 123 = Up"

# Vitaly: "Nexus4 starts working better with WDS suite if you disable
# TCP timestamps".
sudo echo 0 > /proc/sys/net/ipv4/tcp_timestamps

while true; do
echo `/usr/share/jaspar/monitor.py`
  sleep 1;
done | dzen2 -h 128 -fg white -bg black -dock &

# matchbox-desktop is started by jaspar.service
exec matchbox-window-manager -use_titlebar no -theme Sato -use_cursor $SHOWCURSOR
